### ISSUE TITLE
Add http post request to example

### ISSUE THREAD

**Issue by brasilikum** [etaque/elm-form#28]
I am trying to get going with elm and I would really appreciate it if you could add an example about how to send this to a certain endpoint via http post, because in my static site the contact form is the only dynamic part I want and I would like to do it all in elm.
This might be slightly off topic, but from my point of view would make it easier for users new to elm to replace their jQuery clutter
Thanks for considering

**Comment by brasilikum** [comment]
Ok I found out it does, but only to the same url it is served from, right?
Form.Submit does not accept a path, right?

**Comment by etaque** [comment]
Hello,
HTTP is out of the scope of this package because form submitting doesn't mean sending to server here, just retrieving a valid record.
Also if you're beginning with Elm and just need a contact form you might better do that in pure Elm. I suggest to join the Elm slack channel for help:
http://elmlang.herokuapp.com/

Cheers
