### ISSUE TITLE
Considering a rename to elm-form

### ISSUE THREAD

**Issue by etaque** [etaque/elm-form#61]
As this package isn't really targeted for simple forms, and offers at the same time form building and validation, I'm tempted to do this rename.

(I'm aware of the procedure to avoid broken builds)

WDYT?

**Comment by pablohirafuji** [comment]
When I first saw this package, because of the "simple", I had some prejudice. But at that time, my project was also simple, so I used it.

As my project grow (10.000+ lines of Elm), this package is still robust and flexible enough for all my form needs. My project makes heavy use of forms (20+ different forms) and I am grateful for had choosing to use this package.

So, yeah, I really like this idea!

**Comment by Guid75** [comment]
I'm 200% for this  change, and it's of course not related to the fact I am one of the folks who suggested it to you :-)

**Comment by etaque** [comment]
Done! (but package not published yet)
